// Generated by gencpp from file ig_action_msgs/InstructionGraphGoal.msg
// DO NOT EDIT!


#ifndef IG_ACTION_MSGS_MESSAGE_INSTRUCTIONGRAPHGOAL_H
#define IG_ACTION_MSGS_MESSAGE_INSTRUCTIONGRAPHGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ig_action_msgs
{
template <class ContainerAllocator>
struct InstructionGraphGoal_
{
  typedef InstructionGraphGoal_<ContainerAllocator> Type;

  InstructionGraphGoal_()
    : order()  {
    }
  InstructionGraphGoal_(const ContainerAllocator& _alloc)
    : order(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _order_type;
  _order_type order;




  typedef boost::shared_ptr< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> const> ConstPtr;

}; // struct InstructionGraphGoal_

typedef ::ig_action_msgs::InstructionGraphGoal_<std::allocator<void> > InstructionGraphGoal;

typedef boost::shared_ptr< ::ig_action_msgs::InstructionGraphGoal > InstructionGraphGoalPtr;
typedef boost::shared_ptr< ::ig_action_msgs::InstructionGraphGoal const> InstructionGraphGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ig_action_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ig_action_msgs': ['/home/jaholtz/LLStaging-master/installation/catkin_ws/devel/share/ig_action_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9db207449ae86824d9e60bd906ef30e7";
  }

  static const char* value(const ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9db207449ae86824ULL;
  static const uint64_t static_value2 = 0xd9e60bd906ef30e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ig_action_msgs/InstructionGraphGoal";
  }

  static const char* value(const ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
string order\n\
";
  }

  static const char* value(const ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct InstructionGraphGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ig_action_msgs::InstructionGraphGoal_<ContainerAllocator>& v)
  {
    s << indent << "order: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IG_ACTION_MSGS_MESSAGE_INSTRUCTIONGRAPHGOAL_H
