// Auto-generated. Do not edit!

// (in-package ig_action_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class InstructionGraphGoal {
  constructor() {
    this.order = '';
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type InstructionGraphGoal
    // Serialize message field [order]
    bufferInfo = _serializer.string(obj.order, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type InstructionGraphGoal
    let tmp;
    let len;
    let data = new InstructionGraphGoal();
    // Deserialize message field [order]
    tmp = _deserializer.string(buffer);
    data.order = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'ig_action_msgs/InstructionGraphGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9db207449ae86824d9e60bd906ef30e7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    string order
    
    `;
  }

};

module.exports = InstructionGraphGoal;
