(cl:defpackage ig_action_msgs-msg
  (:use )
  (:export
   "<INSTRUCTIONGRAPHACTION>"
   "INSTRUCTIONGRAPHACTION"
   "<INSTRUCTIONGRAPHACTIONFEEDBACK>"
   "INSTRUCTIONGRAPHACTIONFEEDBACK"
   "<INSTRUCTIONGRAPHACTIONGOAL>"
   "INSTRUCTIONGRAPHACTIONGOAL"
   "<INSTRUCTIONGRAPHACTIONRESULT>"
   "INSTRUCTIONGRAPHACTIONRESULT"
   "<INSTRUCTIONGRAPHFEEDBACK>"
   "INSTRUCTIONGRAPHFEEDBACK"
   "<INSTRUCTIONGRAPHGOAL>"
   "INSTRUCTIONGRAPHGOAL"
   "<INSTRUCTIONGRAPHRESULT>"
   "INSTRUCTIONGRAPHRESULT"
  ))

