; Auto-generated. Do not edit!


(cl:in-package ig_action_msgs-msg)


;//! \htmlinclude InstructionGraphActionGoal.msg.html

(cl:defclass <InstructionGraphActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type ig_action_msgs-msg:InstructionGraphGoal
    :initform (cl:make-instance 'ig_action_msgs-msg:InstructionGraphGoal)))
)

(cl:defclass InstructionGraphActionGoal (<InstructionGraphActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <InstructionGraphActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'InstructionGraphActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ig_action_msgs-msg:<InstructionGraphActionGoal> is deprecated: use ig_action_msgs-msg:InstructionGraphActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <InstructionGraphActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ig_action_msgs-msg:header-val is deprecated.  Use ig_action_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <InstructionGraphActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ig_action_msgs-msg:goal_id-val is deprecated.  Use ig_action_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <InstructionGraphActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ig_action_msgs-msg:goal-val is deprecated.  Use ig_action_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <InstructionGraphActionGoal>) ostream)
  "Serializes a message object of type '<InstructionGraphActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <InstructionGraphActionGoal>) istream)
  "Deserializes a message object of type '<InstructionGraphActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<InstructionGraphActionGoal>)))
  "Returns string type for a message object of type '<InstructionGraphActionGoal>"
  "ig_action_msgs/InstructionGraphActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'InstructionGraphActionGoal)))
  "Returns string type for a message object of type 'InstructionGraphActionGoal"
  "ig_action_msgs/InstructionGraphActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<InstructionGraphActionGoal>)))
  "Returns md5sum for a message object of type '<InstructionGraphActionGoal>"
  "bc4a6831132b921482d6b6d7fca2dc08")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'InstructionGraphActionGoal)))
  "Returns md5sum for a message object of type 'InstructionGraphActionGoal"
  "bc4a6831132b921482d6b6d7fca2dc08")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<InstructionGraphActionGoal>)))
  "Returns full string definition for message of type '<InstructionGraphActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%InstructionGraphGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: ig_action_msgs/InstructionGraphGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'InstructionGraphActionGoal)))
  "Returns full string definition for message of type 'InstructionGraphActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%InstructionGraphGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: ig_action_msgs/InstructionGraphGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <InstructionGraphActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <InstructionGraphActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'InstructionGraphActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
